### ISSUE TITLE
0.1.0 开发计划

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#7]
### 规划
- [x] #10 想个好名字
- [x] #9 整体技术方案
### driver
- [x] #11 跑通 thrill + queen + selenium grid
- [x] #21 确认package.json 中的配置项
- [x] #13 runner 拼装方案
- [x] #8 命令行参数
- [x] #22 解决 queen 同类浏览器重复运行单元测试的问题
- [x] #23 使用 totoro 测试 arale 基础模块
- [x] #28 定位和修复 arale 测试中发现的测试框架的问题
### 选择单元测试框架
- [x] 测试基础知识
- [x] 套件
- [x] 断言
- [x] #17 翻译 sinon 文档，转换成cmd模块发布到源
- [x] #18 事件模拟
### 生产环境部署
- [x] #14 申请测试服务器
- [x]  #16 部署服务端代码 
### 文档
- [x] #20 测试系统设计方案
- [x] #19 测试基础知识ppt
